{% set name = "nlpaug" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/makcedward/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 02fb6b48d67b0a495dfe079b550ebf84e9c014c1bace8a68cb613612d072acea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy >=1.16.2
    - python >=3.6
    - requests >=2.22.0

test:
  imports:
    - nlpaug
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/makcedward/nlpaug
  license: MIT
  license_file: LICENSE
  summary: Natrual language processing data Augmentation library
  description: |
    This python library helps you with augmenting NLP for your machine learning
     projects. `Augmenter` is the basic element of augmentation while `Flow` is
     a pipeline to orchestra multi augmenter together. Nlpaug generates
     synthetic data for improving model performance without manual effort. It is
     a simple and easy-to-use and lightweight library where you can augment data
     in 3 lines of code, and features plug and play to any machine leanring
     and neural network frameworks (e.g. scikit-learn, PyTorch, TensorFlow).
     Nlpaug supports textual and audio input as well.


extra:
  recipe-maintainers:
    - thewchan
